name: metrics
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.33      # 降级，网络友好
        with:
          token: ${{ secrets.STATS_TOKEN }} # 一定是你刚生成的 PAT
          filename: metrics.svg
          output: svg
          base: header, activity             # 只拉最少数据