name: metrics
on:
  workflow_dispatch:          # 手动点火必须有
  push:
    branches: [main]          # 推送到 main 也触发一次
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.STATS_TOKEN }}
          filename: metrics.svg
          output: svg
          base: header, activity